version: '3.8'

services:
  
  minio:
    image: minio/minio
    container_name: data-lake-minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    command: server /data --console-address ":9001"

  postgres:
    image: postgres:13
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
      POSTGRES_DB: elt
    ports:
      - "5435:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  trino:
    image: trinodb/trino
    container_name: trino
    ports:
      - "8081:8080"  # Trino Web UI
    depends_on:
      - minio

  airflow:
    image: puckel/docker-airflow
    container_name: airflow
    restart: always
    depends_on:
      - postgres
      - minio
    environment:
      - LOAD_EX=n
      - AIRFLOW__CORE__EXECUTOR=SequentialExecutor
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://postgres:postgres123@postgres:5432/elt
    volumes:
      - ./dags:/usr/local/airflow/dags
    ports:
      - "8082:8080"  # Airflow UI

volumes:
  minio_data:
  postgres_data:
